CREATE TABLE IF NOT EXISTS calculations (
    id SERIAL PRIMARY KEY,
    operation VARCHAR(20) NOT NULL,
    a DOUBLE PRECISION NOT NULL,
    b DOUBLE PRECISION NOT NULL,
    result DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
